<template>
  <div>
    <Header msg="LOG IN" selectedUser="selected-header" />
    <main>
      <section>
        <div id="user_inform" class="layout">
          <div class="title">
            <span class="title">USER INFORMATION</span>
            <button @click="handleClick">LOG OUT</button>
          </div>

          <!-- this data need to generate auto by system -->
          <div id="information">
            <i class="far fa-user-circle icon-user"></i>
            <span style="margin-right: 0.5rem">Name : </span>
            <span>{{ user.displayName }}</span>
            <!-- name must be taken from system when user sign up -->
          </div>
          <div id="information">
            <i class="far fa-user-circle icon-user"></i>
            <span style="margin-right: 0.5rem">Name : </span>
            <span>{{ user.displayName }}</span>
            <!-- name must be taken from system when user sign up -->
          </div>
          <div id="information">
            <i class="far fa-credit-card icon-user" style="font-size: 18px"></i>
            <span style="margin-right: 0.5rem;">
              CUSTOMER ID :
            </span>
            <span>2340554433</span>
            <!-- id must be generated by system -->
          </div>
        </div>
        <div id="card_payment" class="layout">
          <div class="title">
            <span class="title">CARD & PAYMENT</span>
          </div>

          <!-- a user can  have more than one card
          and this div maybe need to loop, and also take data from datbase  -->
          <div class="credit_card">
            <div style="display: flex;">
              <i
              class="fab fa-cc-visa"
              style="font-size: 40px; margin-right: 0.5rem"
            ></i>
            <div class="card_infor">
              <span>**** **** **** 7444</span>
              <span>Expiation 01/23</span>
            </div>
            </div>
            <!-- there are several kind of credit card such paypal, visa, master, ... -->
            <button>
              REMOVE
              <i class="far fa-times-circle"></i>
            </button>
          </div>
        </div>
        <div id="wishlists" class="layout">
          <div class="title">
            <span class="title">YOUR WISHLISTS</span>
          </div>
          <div class="item_buy">
            <div class="img_title">
              <div class="img_game"></div>
              <ul>
                <li>GAME TITLE</li>
                <li>GAME DESCRIPTION</li>
                <li style="text-decoration: line-through">20000 RIELS</li>
                <li>10000 RIELS</li>
                <li>AVERAGE STAR: 4.5/5</li>
              </ul>
            </div>
            <button class="checkout">
              CHECKOUT <i class="fas fa-shopping-cart"></i>
            </button>
          </div>
        </div>
      </section>
    </main>
    <Footer />
  </div>
</template>

<script>
import Header from "./Header";
import Footer from "./Footer";
import getUser from '../composables/getUser'
import useLogout from '../composables/useLogout'
import {useRouter} from 'vue-router'
import {watch} from 'vue'
export default {
  name: "userpage",
  components: {
    Header,
    Footer,
  },
  setup() {
		const {error,logout} = useLogout();
		const {user} = getUser();
		const router = useRouter();

		const handleClick =  async() => {
			await logout()
			if(!error.value){
				console.log("User Log out")
			}
		}
    watch(user,()=>{
			if(!user.value){
				router.push('/')
			}
		});

		return {
			handleClick, user
		}
	},
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap");
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
main {
  color: white;
  font-family: "Ubuntu";
  font-style: normal;
  font-weight: bold;
  font-size: 16px;
  background-color: #303841;
}
main > section {
  display: block;
  align-items: center;
  padding: 2rem 10rem 2rem 10rem;
}
div.layout {
  height: 22rem;
  margin-top: 2rem;
}
div#user_inform {
  margin: 0;
}
div#information {
  display: flex;
  align-items: center;
}
div#information .icon-user {
  font-size: 20px;
  margin-right: 1rem;
}
div.layout div.title {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 15px;
  border-bottom: white solid 2px;
  margin-bottom: 2rem;
}
div#user_inform button {
  padding: 10px 20px 10px 20px;
  background: red;
  border: none;
  border-radius: 50px;
  font-weight: bolder;
  color: white;
  cursor: pointer;
}
div.credit_card {
  border: 2px solid red;
  padding: 2px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
div.credit_card > button {
  color: aliceblue;
  background-color: red;
  font-weight: 900;
  width: 5rem;
  font-size: 10px;
  border-radius: 50px;
  border: none;
  width: 4.5rem;
  padding: 2px 0 2px 0 ;
  margin-right: 1rem;
}
div.card_infor {
  display: grid;
  font-size: 10px;
  margin-left: 5rem;
}
div.item_buy {
  height: 15rem;
  margin-top: 3rem;
  align-items: flex-end;
  display: flex;
  justify-content: space-between;
}
.img_title {
  height: 100%;
  display: flex;
  align-items: flex-end;
}
.img_game {
  height: 100%;
  width: 12rem;
  background-color: rgb(170, 163, 149);
}
div.item_buy ul {
  list-style: none;
  padding-left: 2rem;
}
button.checkout {
  border: none;
  border-radius: 50px;
  padding: 10px 20px 10px 20px;
  background-color: red;
  color: white;
  font-weight: bolder;
  cursor: pointer;
}
div#wishlists {
  border-bottom: white solid 2px;
}
</style>